upstream edugrade_api {
  server api-gateway:8080;
}

upstream edugrade_web {
  server web-admin:80;
}

upstream edugrade_ai_placeholder {
  server ai-services-placeholder:8100;
}

server {
  listen 80;
  server_name _;

  client_max_body_size 110m;

  location = /health {
    access_log off;
    return 200 "nginx ok\n";
    add_header Content-Type text/plain;
  }

  location /api/ {
    proxy_pass http://edugrade_api;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }

  location /ready {
    proxy_pass http://edugrade_api;
  }

  location /backend-health {
    proxy_pass http://edugrade_api/health;
  }

  location /ai-placeholder/ {
    proxy_pass http://edugrade_ai_placeholder/;
  }

  location / {
    proxy_pass http://edugrade_web;
    proxy_http_version 1.1;
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
    proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
    proxy_set_header X-Forwarded-Proto $scheme;
  }
}
